{
 "title": "Printer Filament Stats",
 "time": { "from": "now-2y", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "printers",
    "label": "Printer",
    "query": "select distinct printer from prints where material_type = 'filament';"
   },
   {
    "name": "materials_bkp",
    "label": "Materials bkp",
    "query": "select distinct(material) from prints where material is not NULL and printer = '${printers}'"
   },
   {
    "name": "materials",
    "label": "Materials",
    "query": "select distinct(b->>'type') from (select JSONB_ARRAY_ELEMENTS(filament_data) as b from prints where jsonb_array_length( filament_data ) != 0 and printer = '${printers}' ) as foo"
   }
  ]
 },
 "panels": [
  { "title": "Amount By Material", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "${materials}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3.4285714285714284, "x": 0, "y": 1 },
   "repeat": "materials",
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n      sum( CASE WHEN (b->>'used_g')::float = 0.0 and material_used > 0 and most_mat = '$materials' and most_mat = (b->>'type')::text THEN material_used  ELSE ( (b->>'used_g')::float * (progress_done / 100) ) END),\r\n       (b->>'type')::text as material\r\n      from (\r\n            SELECT JSONB_ARRAY_ELEMENTS(filament_data) as b, progress_done, material as most_mat, material_used\r\n            from prints \r\n            where jsonb_array_length(filament_data) != 0 \r\n            and printer = '${printers}' \r\n            and $__timeFilter(start_time)\r\n      ) as foo \r\n      where (b->>'type')::text = '$materials' group by material"
    }
   ]
  },
  { "title": "Hours By Material", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "$materials",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3.4285714285714284, "x": 0, "y": 7 },
   "repeat": "materials",
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n      sum(case when prints.status = 'RUNNING' or prints.status = 'PAUSED' then EXTRACT(EPOCH FROM ((now() at time zone 'utc') - start_time)) else EXTRACT(EPOCH FROM (end_time - start_time))end),\r\n       material from prints where $__timeFilter(start_time) and material = '$materials' and printer = '${printers}' group by material"
    }
   ]
  },
  { "title": "KwH Per Material", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$materials",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3.4285714285714284, "x": 0, "y": 13 },
   "repeat": "materials",
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n      sum(kwh) as \"KwH\",\r\n       material from prints where $__timeFilter(start_time) and material = '$materials' and printer = '${printers}' group by material"
    }
   ]
  },
  { "title": "Material Cost By Material", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "$materials",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3.4285714285714284, "x": 0, "y": 19 },
   "repeat": "materials",
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n      sum( CASE WHEN (b->>'used_cost')::float = 0.0 and material_used_cost > 0 and most_mat = '$materials' and most_mat = (b->>'type')::text THEN material_used_cost  ELSE ( (b->>'used_cost')::float * (progress_done / 100) ) END),\r\n      (b->>'type')::text as material \r\n      from (\r\n            SELECT JSONB_ARRAY_ELEMENTS(filament_data) as b , progress_done, material_used_cost, material as most_mat\r\n            from prints \r\n            where jsonb_array_length(filament_data) != 0 \r\n            and printer = '${printers}' \r\n            and $__timeFilter(start_time)\r\n      ) as foo \r\n      where (b->>'type')::text = '$materials' group by material"
    }
   ]
  },
  {
   "title": "Complete Print Stats Summary - $printers",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "select\r\n      sum( CASE WHEN (b->>'used_g')::float = 0.0 and (b->>'type')::text = most_mat and material_used > 0 THEN material_used  ELSE ( (b->>'used_g')::float * (progress_done / 100) ) END) as \"amount\",\r\n      (CASE when material_type = 'resin' then 'ml' else 'g' end) as \"material_unit\",\r\n      sum(case when status = 'RUNNING' or status = 'PAUSED' then EXTRACT(EPOCH FROM ((now() at time zone 'utc') - start_time)) else EXTRACT(EPOCH FROM (end_time - start_time))end) as \"duration\",\r\n      sum(kwh) as \"KwH\",\r\n      sum(( (b->>'used_cost')::float * (progress_done / 100) ))as \"Material Cost\",\r\n       (b->>'type')::text as material from \r\n       (select jsonb_array_elements(filament_data) as b, material_type, status, start_time, end_time, kwh, progress_done, material as most_mat, material_used\r\n       from prints where $__timeFilter(start_time) and material is not null and printer = '${printers}') as foo group by material, material_type"
    }
   ]
  }
 ]
}