{
 "title": "Printer Stats",
 "time": { "from": "now-2y", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "printers",
    "label": "Printer",
    "query": "select distinct printer from prints where material_type = 'filament';"
   },
   {
    "name": "ignored",
    "query": "filament_unload.gcode,filament_baker_gcode_prepare.gcode,auto_cali_for_user_param.gcode,abs_flowcalib_cali.gcode,auto_filament_cali.gcode"
   },
   { "name": "minkwh", "label": "Min wH", "query": "0" },
   {
    "name": "materials",
    "label": "Materials",
    "query": "select distinct(b->>'type') from (select JSONB_ARRAY_ELEMENTS(filament_data) as b from prints where jsonb_array_length( filament_data ) != 0 and printer = '${printers}' ) as foo"
   }
  ]
 },
 "panels": [
  { "title": "Amounts By Material", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$materials",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3.4285714285714284, "x": 0, "y": 1 },
   "repeat": "materials",
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n      sum( CASE WHEN (b->>'used_g')::float = 0.0 and material_used > 0 and most_mat = $materials and most_mat = (b->>'type')::text THEN material_used  ELSE ( (b->>'used_g')::float * (progress_done / 100) ) END),\r\n        (CASE when material_type = 'resin' then 'ml' else 'g' end) as \"material_unit\", (b->>'type')::text as material\r\n      from (\r\n            SELECT JSONB_ARRAY_ELEMENTS(filament_data) as b, material_type, progress_done, material as most_mat, material_used\r\n            from prints \r\n            where jsonb_array_length(filament_data) != 0 \r\n            and printer = '${printers}' \r\n            and $__timeFilter(start_time)\r\n      ) as foo \r\n      where (b->>'type')::text = $materials group by material, material_type"
    }
   ]
  },
  { "title": "Hours By Material", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "$materials",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3.4285714285714284, "x": 0, "y": 7 },
   "repeat": "materials",
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n      sum(case when prints.status = 'RUNNING' or prints.status = 'PAUSED' then EXTRACT(EPOCH FROM ((now() at time zone 'utc') - start_time)) else EXTRACT(EPOCH FROM (end_time - start_time))end),\r\n       material from prints where $__timeFilter(start_time) and material = $materials and printer = '${printers}' group by material"
    }
   ]
  },
  { "title": "KwH Per Material", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$materials",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3.4285714285714284, "x": 0, "y": 13 },
   "repeat": "materials",
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n      sum(kwh) as \"KwH\",\r\n       material from prints where $__timeFilter(start_time) and material = $materials and printer = '${printers}' group by material"
    }
   ]
  },
  { "title": "Filament Cost By Material", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "$materials",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3.4285714285714284, "x": 0, "y": 19 },
   "repeat": "materials",
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n      sum( CASE WHEN (b->>'used_cost')::float = 0.0 and material_used_cost > 0 and most_mat = $materials and most_mat = (b->>'type')::text THEN material_used_cost  ELSE ( (b->>'used_cost')::float * (progress_done / 100) ) END),\r\n      (b->>'type')::text as material \r\n      from (\r\n            SELECT JSONB_ARRAY_ELEMENTS(filament_data) as b , progress_done, material_used_cost, material as most_mat\r\n            from prints \r\n            where jsonb_array_length(filament_data) != 0 \r\n            and printer = '${printers}' \r\n            and $__timeFilter(start_time)\r\n      ) as foo \r\n      where (b->>'type')::text = $materials group by material"
    }
   ]
  },
  { "title": "Base", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "List of Prints",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT prints.printer, prints.start_time,\r\n      prints.name, prints.status,\r\n      (CASE when prints.status = 'RUNNING' or prints.status = 'PAUSED' THEN (total.kwh - prints.initial_kwh) ELSE prints.kwh END) as kwh,\r\n      (CASE when prints.status = 'RUNNING' or prints.status = 'PAUSED' THEN ((total.kwh - prints.initial_kwh) * (prints.electric_rate / 100)) ELSE prints.electric_cost END) as \"electric_cost\",\r\n      (case when prints.status = 'RUNNING' or prints.status = 'PAUSED' then EXTRACT(EPOCH FROM ((now() at time zone 'utc') - prints.start_time)) else EXTRACT(EPOCH FROM (prints.end_time - prints.start_time))end) as duration,\r\n      prints.material_used, prints.material_used_cost, (CASE when prints.material_type = 'resin' then 'ml' else 'g' end) as \"material_unit\", material, plate_type, filament_data, progress_done\r\nFROM prints,\r\n  ( SELECT kwh, printer FROM energy_reading\r\n        WHERE printer = '${printers}'\r\n        LIMIT 1\r\n    )\r\n total\r\nWHERE $__timeFilter(start_time) AND prints.printer = total.printer and prints.printer = '${printers}' and prints.name not in (${ignored}) and \r\n      (CASE when prints.status = 'RUNNING' or prints.status = 'PAUSED' THEN (total.kwh - prints.initial_kwh) ELSE prints.kwh END) > ${minkwh}\r\nORDER BY prints.start_time DESC"
    }
   ]
  },
  {
   "title": "Total Costs (Energy)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT kwh as \"kWh\", \r\n      ((rate / 100) * kwh ) as \"Cost\" \r\nFROM (\r\n        SELECT printer, electric_rate as rate ,\r\n               kwh FROM energy_reading\r\n               WHERE printer = '${printers}'\r\n        --WHERE $__timeFilter(read_time)\r\n        LIMIT 1\r\n    )\r\n t WHERE printer = '${printers}'"
    }
   ]
  },
  {
   "title": "Printing Costs (Energy)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(kwh) as \"kWh\", \r\nsum(electric_cost) as \"Cost\" \r\nFROM prints \r\nWHERE --$__timeFilter(start_time) AND \r\nprinter = '${printers}' and prints.name not in (${ignored})"
    }
   ]
  },
  {
   "title": "Idle Costs (Energy)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT (total.kwh - print.kwh) as \"kWh\", \r\n       (total.cost - print.cost) as \"Cost\" \r\nfrom  (SELECT sum(kwh) as \"kwh\", \r\n              sum(electric_cost) as \"cost\"\r\n       FROM prints WHERE \r\n       --$__timeFilter(start_time) AND \r\n       printer = '${printers}' and name not in (${ignored})) print, \r\n      (SELECT kwh as \"kwh\",\r\n             ((rate / 100) * kwh ) as \"cost\" \r\n      FROM \r\n          (SELECT printer, electric_rate as rate ,\r\n                   kwh FROM energy_reading \r\n          WHERE-- $__timeFilter(read_time) AND\r\n           printer = '${printers}'\r\n           LIMIT 1) \r\n      t) \r\ntotal"
    }
   ]
  },
  {
   "title": "Printing Costs (Material)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "      select \r\n      sum(((b->>'used_g')::float * (progress_done / 100)))as \"Amount\", sum(((b->>'used_cost')::float) * (progress_done / 100)) as \"Cost\",  (CASE when material_type = 'resin' then 'ml' else 'g' end) as \"material_unit\"\r\n      from (\r\n            SELECT JSONB_ARRAY_ELEMENTS(filament_data) as b, material_type, progress_done\r\n            from prints \r\n            where jsonb_array_length(filament_data) != 0 \r\n            and printer = '${printers}' \r\n            and $__timeFilter(start_time)\r\n      ) as foo group by material_type\r\n      "
    }
   ]
  }
 ]
}